CREATE SCHEMA IF NOT EXISTS autoservice;
CREATE SCHEMA IF NOT EXISTS customer;
CREATE SCHEMA IF NOT EXISTS dictionary;
CREATE SCHEMA IF NOT EXISTS history;
CREATE SCHEMA IF NOT EXISTS humanresource;
CREATE SCHEMA IF NOT EXISTS whsync;

